### ISSUE TITLE
Node object is not a node-red Node error

### ISSUE THREAD

**Issue by maruthi268** [AmyAmy/node-red-contrib-moving-average#11]
Getting this warning when an undefined vaiable payload is passed in raspberry pi

Posting issue on request : [https://discourse.nodered.org/t/node-object-is-not-a-node-red-node-error/66262](url)

```node-red-log

11 Aug 15:01:00 - [error]

Unexpected Node Error

Info:
 Node object is not a node-red Node
Stack:
 Error: Invalid payload type (undefined): expected number, boolean, string
    at log_helper (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:512:20)
    at Node.error (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:553:9)
    at parsePayload (/home/pi/.node-red/node_modules/node-red-contrib-moving-average/moving-average.js:49:13)
    at MovingAverageNode._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-moving-average/moving-average.js:64:39)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at MovingAverageNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at MovingAverageNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at MovingAverageNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (internal/timers.js:464:21)
Please report this issue, including the information logged above:
https://github.com/node-red/node-red/issues/

```

**Comment by logicalshrapnel** [comment]
Not a solution but a workaround I found is to make sure you cast the data to a number using a change node. Feeding it a number as a string gave this exact issue.
Also make sure the topic does not contain a space as this too will break it,
